"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.useToggle = exports.useLocalStorage = exports.useDelete = exports.usePut = exports.usePost = exports.useGet = exports.useFetch = void 0;
var useFetch_1 = require("./src/useFetch");
Object.defineProperty(exports, "useFetch", { enumerable: true, get: function () { return __importDefault(useFetch_1).default; } });
var useGet_1 = require("./src/useGet");
Object.defineProperty(exports, "useGet", { enumerable: true, get: function () { return __importDefault(useGet_1).default; } });
var usePost_1 = require("./src/usePost");
Object.defineProperty(exports, "usePost", { enumerable: true, get: function () { return __importDefault(usePost_1).default; } });
var usePut_1 = require("./src/usePut");
Object.defineProperty(exports, "usePut", { enumerable: true, get: function () { return __importDefault(usePut_1).default; } });
var useDelete_1 = require("./src/useDelete");
Object.defineProperty(exports, "useDelete", { enumerable: true, get: function () { return __importDefault(useDelete_1).default; } });
var useLocalStorage_1 = require("./src/useLocalStorage");
Object.defineProperty(exports, "useLocalStorage", { enumerable: true, get: function () { return __importDefault(useLocalStorage_1).default; } });
var useToggle_1 = require("./src/useToggle");
Object.defineProperty(exports, "useToggle", { enumerable: true, get: function () { return __importDefault(useToggle_1).default; } });
